services:
  - type: web
    name: fuwari-blog
    runtime: node
    plan: free
    region: singapore
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/server/entry.mjs
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: OAUTH_GITHUB_CLIENT_ID
        sync: false
      - key: OAUTH_GITHUB_CLIENT_SECRET
        sync: false
      - key: PUBLIC_DECAP_CMS_SRC_URL
        value: https://unpkg.com/decap-cms@^3/dist/decap-cms.js
    autoDeploy: true
